# Generated by Django 4.0.6 on 2022-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priolity',
            field=models.IntegerField(choices=[(1, '1:低い'), (2, '2:少し低い'), (3, '3:普通'), (4, '4:少し高い'), (5, '5:高い')], default=3),
        ),
    ]
